// AUTO-GENERATED by KeyBaker.exe from VendorSigningKey_Public.pem - do not edit by hand.
// Regenerate by running KeyBaker.exe whenever the vendor key pair changes.
namespace NutriculaInstaller
{
    internal static class VendorPublicKeyEmbedded
    {
        public static readonly byte[] X = { 147,32,69,212,184,10,61,195,159,105,106,193,85,23,13,154,121,72,121,169,73,114,147,206,155,122,141,187,140,196,96,183 };
        public static readonly byte[] Y = { 1,30,150,120,243,85,103,70,160,243,224,179,7,227,239,114,62,207,220,216,234,4,52,170,158,19,46,200,11,187,58,138 };
    }
}
