// AUTO-GENERATED by KeyBaker.exe from CoordinatorIdentityKey_Public.pem - do not edit by hand.
"-----BEGIN PUBLIC KEY-----\n"
"MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEiv9qHN0ThlO/RHRDk2sRZk92PyB+W0bN\n"
"SUptVMcKi9dbCFIGLjkXZbgE0z7ZgBMFHwjYf07aot81BkkmuprpHw8YSeeJckGk\n"
"5AvK1r/bwjmoESIm0AepjALcnstD5RtM\n"
"-----END PUBLIC KEY-----\n"
