// AUTO-GENERATED by KeyBaker.exe from CoordinatorIdentityKey_Private.pem - do not edit by hand.
"-----BEGIN EC PRIVATE KEY-----\n"
"MIGkAgEBBDDM5mZ0cSKQjh0X1ZyXa4dqq7O8VDAGJbqJElaRgp9ClQTRMQh4qKIQ\n"
"fsYjvGlFMUWgBwYFK4EEACKhZANiAASK/2oc3ROGU79EdEOTaxFmT3Y/IH5bRs1J\n"
"Sm1UxwqL11sIUgYuORdluATTPtmAEwUfCNh/Ttqi3zUGSSa6mukfDxhJ54lyQaTk\n"
"C8rWv9vCOagRIibQB6mMAtyey0PlG0w=\n"
"-----END EC PRIVATE KEY-----\n"
