// AUTO-GENERATED by KeyBaker.exe from VendorSigningKey_Private.pem - do not edit by hand.
"-----BEGIN EC PRIVATE KEY-----\n"
"MIGkAgEBBDCvH5ESnmTbyoLakmlZeVhe8J8Lr71PLwz3J+EqpC47F5NCgViiw8jI\n"
"bPrB9WdEF+egBwYFK4EEACKhZANiAAQRj/IgNvzzFSWVe3A52dKVhlX7G8xTpVRg\n"
"p6u+Iz2c+q57Dq+GWYHjkDLZhX1gRsAq4wL1aqBQrZJcb9LiaQpHLN66SN0QMNsv\n"
"4OpT2VQ0G562RcsoD4uZq939/hk9jHA=\n"
"-----END EC PRIVATE KEY-----\n"
