// AUTO-GENERATED by KeyBaker.exe from VendorSigningKey_Public.pem - do not edit by hand.
"-----BEGIN PUBLIC KEY-----\n"
"MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEEY/yIDb88xUllXtwOdnSlYZV+xvMU6VU\n"
"YKerviM9nPquew6vhlmB45Ay2YV9YEbAKuMC9WqgUK2SXG/S4mkKRyzeukjdEDDb\n"
"L+DqU9lUNBuetkXLKA+Lmavd/f4ZPYxw\n"
"-----END PUBLIC KEY-----\n"
